version: '3.8'
services:
  postgres:
    image: 'postgres:16.3-alpine'
    environment:
      - 'POSTGRES_DB=gout'
      - 'POSTGRES_USER=gosuriya'
      - 'POSTGRES_PASSWORD=168'
    ports:
      - '5433:5433'
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - '4317:4317'
      - '4318:4318'
      - '3000:3000'