server:
  shutdown: graceful
  port: 4000

spring:
  application:
    name: gout-backend
  # threads.virtual.enabled: true
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  # Database connection - PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/gout}
    username: ${DATABASE_USER:gosuriya}
    password: ${DATABASE_PASSWORD:168}
    hikari:
      maximum-pool-size: ${POOL_SIZE:10}
  # Database migration
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${IS_FLYWAY_BASELINE_ON_MIGRATE:true}
    validate-on-migrate: ${IS_FLYWAY_VALIDATE_ON_MIGRATE:true}
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
